### ISSUE TITLE
Evaluate rejoining `leaves` and `top_half` stores

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/merkle_light#28]
Once we completely transition to a disk-only store (https://github.com/filecoin-project/merkle_light/pull/27) the need to divide the MT in separate files to help offload memory (in the removed `DiskMmapStore` case) should be reevaluated, removing the division would help to significantly simplify the `build` logic.

If we instead determine that such division might be useful we should consider if we should generalize and extend it into a more flexible sub-division where each MT level (or a configurable number that represents X% of the total nodes) has its own `Store`.

**Comment by schomatis** [comment]
We do need to keep those two separated since from the `rust-fil-proofs` side those two stores are processed differently, the leaves are encoded and we need to share them while the top half is built within the MT.

**Comment by schomatis** [comment]
I'm reopening this, talking this over with @cryptonm it became hard for me to actually justify the usefulness of this division. We don't really share the leaves, we copy the `data` into the `leaves_store` and then start MT generation in a new thread.

https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs/src/layered_drgporep.rs#L395-L408

Rejoining this two would be very desirable to simplify the entire MT logic and also https://github.com/filecoin-project/rust-fil-proofs/issues/868 (which now has to accommodate for two files per MT and the bookkeeping it entails).

@cryptonm This may be an interesting task for you because it is very well defined but also it will give you interaction with many aspects of the MT architecture and its interaction with `rust-fil-proofs` (just a thought, this is definitely _not_ a priority and there may be better uses of your time).

**Comment by cryptonm** [comment]
@schomatis I've been reviewing the source since we talked and this makes a lot of sense to me.  I'll talk with the team to find out if this is a priority.

**Comment by cryptonemo** [comment]
https://github.com/filecoin-project/merkle_light/pull/40
